---
server_name: wp-server1
vmid: 9000
client_user: client1

ansible_pubkey: "{{ lookup('file', '/mnt/pve/cephfs/.ssh/id_ed25519.pub') }}"
client_pubkey: "{{ lookup('file', '/mnt/pve/cephfs/.ssh/{{ client_user }}_id_ed25519.pub') }}"