# General network and storage
gateway: 10.24.38.1
nameserver: 8.8.8.8
storage: ceph-pool
ssh_dir: /mnt/pve/cephfs/.ssh
ansible_user: ansible
ansible_private_key_path: "{{ ssh_dir }}/id_ed25519"
ansible_pubkey_path: "{{ ssh_dir }}/id_ed25519.pub"

proxmox_api_host: node1
proxmox_api_user: ansible@pam
proxmox_api_token_id: ansible-token

# LXC container defaults
lxc_template_storage: local
lxc_template_cache_path: /var/lib/vz/template/cache
lxc_template_file: ubuntu-22.04-standard_22.04-1_amd64.tar.zst
lxc_net_rate_mb: 50
lxc_inventory_path: /etc/ansible/hosts
lxc_public_keys_path: "{{ ssh_dir }}/authorized_keys"
lxc_memory: 1024
lxc_cores: 1
lxc_storage_size: 30

# VM Template defaults
template_vmid: 8000
template_name: ubuntu-2404-docker
template_image_path: /var/lib/vz/template/qemu/noble-server-cloudimg-amd64.img
template_memory: 4096
template_cores: 2
template_disk_size_gb: 30

# Monitoring VM defaults
monitoring_vmid: 1200
monitoring_name: monitoring
monitoring_ip: 10.24.38.120


# VM defaults
template_source_node: node1
vm_net_rate_mb: 50

# VM HA defaults
ha_rule_name: wordpress-ha
ha_nodes: node1,node2,node3
ha_rule_strict: false
ha_failback: false

# Inventory
containers:
  - ctid: 201
    hostname: wordpress-lxc-201
    ip: 10.24.38.201
    client_user: client-a

  - ctid: 202
    hostname: wordpress-lxc-202
    ip: 10.24.38.202
    client_user: client-b
  
  - ctid: 203
    hostname: wordpress-lxc-203
    ip: 10.24.38.203
    client_user: client-c

vm_instances:
  - vmid: 1101
    name: wp-client-a
    ip: 10.24.38.111
    client_user: client-a

  - vmid: 1102
    name: wp-client-b
    ip: 10.24.38.112
    client_user: client-b
  
  - vmid: 1103
    name: wp-client-c
    ip: 10.24.38.113
    client_user: client-c

  - vmid: 1104
    name: gitea
    ip: 10.24.38.114
    client_user: gitea

  - vmid: 1105
    name: docker-tutorial
    ip: 10.24.38.115
    client_user: docker


# For destruction
vm_destroy_list: 
  - docker-tutorial


### Wordpress
wordpress_db_name: wordpress_db
wordpress_db_user: wpuser
wordpress_db_password: wpuser
wordpress_download_url: https://wordpress.org/latest.tar.gz
wordpress_archive_path: /tmp/latest.tar.gz
wordpress_extract_path: /tmp
wordpress_source_path: /tmp/wordpress
wordpress_web_root: /var/www/html

