---
# Shared storage where template disks and cloud-init drive should live
template_shared_disk_storage: ceph-pool

# Shared snippet storage reference for cicustom
template_vendor_snippet_storage: cephfs
template_vendor_snippet_name: vendor.yaml
template_vendor_snippet_path: /mnt/pve/cephfs/snippets/vendor.yaml
template_vendor_snippet_ref: '{{ template_vendor_snippet_storage }}:snippets/{{ template_vendor_snippet_name }}'

# Cloud-init vendor snippet content used by the template
template_vendor_snippet_content: |
  #cloud-config
  package_update: true
  package_upgrade: false
  packages:
    - qemu-guest-agent
  runcmd:
    - systemctl enable --now qemu-guest-agent
